name: Workflow de Deploy no GCP

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_REPO_ID: repo-api-ons
      BASEURL_ONS: ${{ secrets.BASEURL_ONS }}
      GCP_BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}
      PACKAGE_ID: ${{ secrets.PACKAGE_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to GCP
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WORKLOAD_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          IMAGE_NAME="${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/$ARTIFACT_REPO_ID/my-app:latest"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: api-cloud-run
          image: ${{env.IMAGE_NAME}}
          region: ${{ secrets.REGION }}
          env_vars: |
            BASEURL_ONS=${{ secrets.BASEURL_ONS }}
            GCP_BUCKET_NAME=${{ secrets.GCP_BUCKET_NAME }}
            PACKAGE_ID=${{ secrets.PACKAGE_ID }}

      - name: Make Cloud Run service public
        run: |
          gcloud run services add-iam-policy-binding api-cloud-run \
            --member="allUsers" \
            --role="roles/run.invoker" \
            --region=${{ secrets.REGION }} \
            --project=${{ secrets.PROJECT_ID }}
